version: 2

builds:
  - main: cmd/main.go
    goos:
      - linux
      - darwin
      - windows

archives:
  - format: binary
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
